### PR TITLE
push the operator to quay.io

### PR DESCRIPTION
**Pull request by haoqing0110**
modify code to push the operator to quay.io.

### CODE REVIEW

**Comment by gyliu513** [comment]
@haoqing0110 PROW is not working for your repo, please update https://github.com/IBM/test-infra/blob/master/prow/cluster/jobs/IBM/healthcheck-service-operator/IBM.healthcheck-service-operator.master.yaml here to fix PROW for your repo.

The `path` is not right for your repo `github.com/IBM/healthcheck-service-operator`, it should be `github.com/IBM/health-service-operator`.

**Comment by gyliu513** [comment]
FYI @morvencao

**Comment by morvencao** [comment]
Check failed, see logs: http://prow.purple-chesterfield.com/log?job=check_healthcheck-service-operator&id=1229734234382405632

**Pull request merged**
