### PR TITLE
 CODE_OF_CONDUCT

### PR DESCRIPTION
**Pull request by gaushikmr**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by haoqing0110** [comment]
@gaushikmr Thanks for the contribution.

**Comment by haoqing0110** [comment]
@gaushikmr lint-markdown checking fail with below errors, could you help replace Bare URL then I can merge it.

```
./CODE_OF_CONDUCT.md:71: MD034 Bare URL used
./CODE_OF_CONDUCT.md:76: MD034 Bare URL used

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
common/Makefile.common.mk:60: recipe for target 'lint-markdown' failed
make: *** [lint-markdown] Error 123
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","time":"2020-07-28T09:01:47Z"}
```

**Comment by gaushikmr** [comment]
@haoqing0110 Ya sure I will do it.

**Comment by gaushikmr** [comment]
@haoqing0110 Can u pls check

**Pull request merged**
